# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: before_deploy
      run: |
        git config.name jiandahao
        git config.email jiandahao@gmail.com
        export TOKEN="${{ secrets.GITHUB_TOKEN }}" 
        sed -i "s/gh_token/${TOKEN}/g" ./_config.yml
    - name: deploy
      run: |
       export CURRENT=${PWD}
       mkdir -p ~/tmp/blog && docker run  --rm -v ~/tmp/blog:/opt/project -w /opt/project jiandahao/hexo:v1.0 hexo init
       docker run  --rm -v ~/tmp/blog:/opt/project -v ${CURRENT}:/opt/project/source/_posts -w /opt/project jiandahao/hexo:v1.0 hexo generate
       docker run  --rm -v ~/tmp/blog:/opt/project -v ${CURRENT}:/opt/project/source/_posts -w /opt/project jiandahao/hexo:v1.0 hexo deploy
